# CRE project target configuration
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://0xrpc.io/sep

staging:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "${WORKFLOW_OWNER_ADDRESS}"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://0xrpc.io/sep
